Update main

diff --git a/main b/main
--- a/main
+++ b/main
@@ -1,24 +1,243 @@
 #!/bin/bash
-select myvar in createDB renameDB dropDB  usedatabase
-do
-	case $myvar in
-		createDB )	
-			read -p "Enter DB Name: " dbname
-			bash dbactions/createdb.sh $dbname
-			;;
-		renameDB )
-			
-			bash dbactions/renamedb.sh
-			;;
-		dropDB )  dbactions/dropdb.sh
-			;;
+mkdir DBMS 2>> ./.error.log
+clear
+echo "Welcome To DBMS"
 
-		usedatabase )
-				bash usedatabase.sh
-			;;
-		* ) echo "what is $REPLY";
-			exit
-			;;
-	esac
+function start {
+  echo "1. Select DB"
+  echo "2. Create DB"
+  echo "3. Rename DB"
+  echo "4. Drop DB"
+  echo "5. Exit"
+  read op
+  case $op in
+    1)  selectDB ;;
+    2) createDB ;;
+    3)  renameDB ;;
+    4)  dropDB ;;
+    5) exit ;;
+    *) echo " Wrong Choice " ; start;
+  esac
+}
 
-done
+function selectDB {
+  echo -e "Enter Database Name: \c"
+  read dbName
+  cd ./DBMS/$dbName 2>>./.error.log
+  if [[ $? == 0 ]]; then
+    echo "Database $dbName was Successfully Selected"
+    tables
+  else
+    echo "Database $dbName wasn't found"
+    start
+  fi
+}
+
+function createDB {
+  echo -e "Enter Database Name: \c"
+  read dbName
+  mkdir ./DBMS/$dbName
+  if [[ $? == 0 ]]
+  then
+    echo "Database Created Successfully"
+  else
+    echo "Error Creating Database $dbName"
+  fi
+  start
+}
+
+function renameDB {
+  echo -e "Enter Current Database Name: \c"
+  read dbName
+  echo -e "Enter New Database Name: \c"
+  read newName
+  mv ./DBMS/$dbName ./DBMS/$newName 2>>./.error.log
+  if [[ $? == 0 ]]; then
+    echo "Database Renamed Successfully"
+  else
+    echo "Error Renaming Database"
+  fi
+  start
+}
+
+function dropDB {
+  echo -e "Enter Database Name: \c"
+  read dbName
+  rm -r ./DBMS/$dbName 2>>./.error.log
+  if [[ $? == 0 ]]; then
+    echo "Database Dropped Successfully"
+  else
+    echo "Database Not found"
+  fi
+  start
+}
+
+function tables {
+  echo -e "Tables"
+  echo "1. Create New Table"
+  echo "2. Insert Into Table"
+  echo "3. Select From Table"
+  echo "4. Drop Table"
+  echo "5. Back To Main Menu"
+  echo "6. Exit"
+
+  echo -e "Enter Choice: \c"
+  read op
+  case $op in
+    1)  createTable ;;
+    2)  insert;;
+    3)  selectMenu ;;
+    4)  dropTable;;
+    5) clear; cd ../.. 2>>./.error.log; start ;;
+    6) exit ;;
+    *) echo " Wrong Choice " ; tables;
+  esac
+
+}
+
+function createTable {
+  echo -e "Table Name: \c"
+  read tableName
+  if [[ -f $tableName ]]; then
+    echo "table already existed ,choose another name"
+    tables
+  fi
+  echo -e "Number of Columns: \c"
+  read colsNum
+  counter=1
+  sep="|"
+  rSep="\n"
+  pKey=""
+  metaData="Field"$sep"Type"$sep"key"
+  while [ $counter -le $colsNum ]
+  do
+    echo -e "Name of Column No.$counter: \c"
+    read colName
+
+    echo -e "Type of Column $colName: "
+    select var in "int" "str"
+    do
+      case $var in
+        int ) colType="int";break;;
+        str ) colType="str";break;;
+        * ) echo "Wrong Choice" ;;
+      esac
+    done
+    if [[ $pKey == "" ]]; then
+      echo -e "Make PrimaryKey ? "
+      select var in "yes" "no"
+      do
+        case $var in
+          yes ) pKey="PK";
+          metaData+=$rSep$colName$sep$colType$sep$pKey;
+          break;;
+          no )
+          metaData+=$rSep$colName$sep$colType$sep""
+          break;;
+          * ) echo "Wrong Choice" ;;
+        esac
+      done
+    else
+      metaData+=$rSep$colName$sep$colType$sep""
+    fi
+    if [[ $counter == $colsNum ]]; then
+      temp=$temp$colName
+    else
+      temp=$temp$colName$sep
+    fi
+    ((counter++))
+  done
+  touch .$tableName
+  echo -e $metaData  >> .$tableName
+  touch $tableName
+  echo -e $temp >> $tableName
+  if [[ $? == 0 ]]
+  then
+    echo "Table Created Successfully"
+    tables
+  else
+    echo "Error Creating Table $tableName"
+    tables
+  fi
+}
+
+function dropTable {
+  echo -e "Enter Table Name: \c"
+  read tName
+  rm $tName .$tName 2>>./.error.log
+  if [[ $? == 0 ]]
+  then
+    echo "Table Dropped Successfully"
+  else
+    echo "Error Dropping Table $tName"
+  fi
+  tables
+}
+
+function insert {
+  echo -e "Table Name: \c"
+  read tableName
+  if ! [[ -f $tableName ]]; then
+    echo "Table $tableName isn't existed ,choose another Table"
+    tables
+  fi
+  colsNum=`awk 'END{print NR}' .$tableName`
+  sep="|"
+  rSep="\n"
+  for (( i = 2; i <= $colsNum; i++ )); do
+    colName=$(awk 'BEGIN{FS="|"}{ if(NR=='$i') print $1}' .$tableName)
+    colType=$( awk 'BEGIN{FS="|"}{if(NR=='$i') print $2}' .$tableName)
+    colKey=$( awk 'BEGIN{FS="|"}{if(NR=='$i') print $3}' .$tableName)
+    echo -e "$colName ($colType) = \c"
+    read data
+
+    # Validate Input
+    if [[ $colType == "int" ]]; then
+      while ! [[ $data =~ ^[0-9]*$ ]]; do
+        echo -e "invalid DataType !!"
+        echo -e "$colName ($colType) = \c"
+        read data
+      done
+    fi
+
+    if [[ $colKey == "PK" ]]; then
+      while [[ true ]]; do
+        if [[ $data =~ ^[`awk 'BEGIN{FS="|" ; ORS=" "}{if(NR != 1)print $(('$i'-1))}' $tableName`]$ ]]; then
+          echo -e "invalid input for Primary Key !!"
+        else
+          break;
+        fi
+        echo -e "$colName ($colType) = \c"
+        read data
+      done
+    fi
+
+    #Set row
+    if [[ $i == $colsNum ]]; then
+      row=$row$data$rSep
+    else
+      row=$row$data$sep
+    fi
+  done
+  echo -e $row"\c" >> $tableName
+  if [[ $? == 0 ]]
+  then
+    echo "Data Inserted Successfully"
+  else
+    echo "Error Inserting Data into Table $tableName"
+  fi
+  row=""
+  tables
+}
+
+
+function selectMenu {
+  echo -e "Enter Table Name: \c"
+  read tName
+  column -t -s '|' $tName 2>>./.error.log
+  if [[ $? != 0 ]]
+  then
+    echo "Error Displaying Table $tName"
+  fi
+  tables
+}
